const ActionTypes = {
  SHOP_ID: "SHOP_ID",
  ADDRESS_DATA: "ADDRESS_DATA",
  ORDER_DATA: "ORDER_DATA",
  USER_DETAILS: "USER_DETAILS",
  SIGNOUT: "SIGNOUT",
  PLACEORDERDATA:"PLACEORDERDATA",
  ERROR:"ERROR",
  LOADER:"LOADER",
  STOREUSERINFO: "STOREUSERINFO",
  UPDATE_USER_PROFILE_DATA:'UPDATE_USER_PROFILE_DATA'
}

export default ActionTypes;
