import React, { Component } from 'react';
import { View, ScrollView, ActivityIndicator, FlatList, Platform,Text } from 'react-native';
// styles
// Container
import AppContainer from '../../Containers/AppContainer';
//component
import Greeting from "../../Components/Greeting";
import Gridmenu from "../../Components/Gridmenu";
import { connect } from 'react-redux';
import { storeUserInfo } from '../../Store/Action/authAction'
import RenderList from "../../Components/RenderList";
import Order from '../../../assets/Home/Order.png'
import lifecycle from 'react-pure-lifecycle';
const url = `http://laundary.debughands.com/api/get-order/`

class Privacy extends Component {
    constructor(props) {
        super(props);
        this.state = {
            OrderHistory: [],
        }
    }


    //   componentWillMount() {
    //     if (this.props.userInfo.user_detail) {
    //       console.log(this.props.userInfo.user_detail, "userInfouserInfo")

    //       fetch(url + this.props.userInfo.user_detail.id, {
    //         method: "GET",
    //         headers: {
    //           'Content-Type': 'application/json'
    //         },
    //       }).then(res => {
    //         return res.json()
    //       }).then(response => {
    //         console.log(response, "222response from backend")
    //         this.setState({ OrderHistory: response.results.data })
    //       })
    //     }

    //   }
    //   _keyExtractor = (item, index) => JSON.stringify(item.id);

    render() {
        const { OrderHistory } = this.state;

        return (
            <AppContainer hideBottomMask={true} footer={true} header={true} title="Privacy & Policy"
                // footerText={true}
                footerButton={false} route="Welcome" >

                <View style={{padding:25}}>
                    <Text style={{color:"black"}}>
                    laundary.com ("us", "we", or "our") operates the http://laundary.com/ website and the laundary.com mobile application (hereinafter referred to as the "Service").
            </Text>
            <Text style={{color:"black",marginTop:15}}>
            This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data. The Privacy Policy for laundary.com has been created with the help ofTermsFeed.
            </Text>
            <Text style={{color:"black",marginTop:15}}>
            We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
            </Text>
            <Text style={{color:"black",marginTop:15,fontSize:22,fontWeight:"bold"}}>
            Definitions
            </Text>
            <Text style={{color:"black",marginTop:15,fontSize:22,fontWeight:"bold"}}>
            •	Service
            </Text>
            <Text style={{color:"black",marginTop:15,padding:15}}>
            Service means the http://laundary.com/ website and the laundary.com mobile application operated by laundary.com
            </Text>
            <Text style={{color:"black",marginTop:15,fontSize:22,fontWeight:"bold"}}>
            •	Personal Data
            </Text>
            {/* <Text style={{color:"black",marginTop:15,padding:15}}> */}
            <Text style={{color:"black",marginTop:15,padding:15}}>
            Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession). 
            
           </Text>
           <Text style={{color:"black",marginTop:15,fontSize:22,fontWeight:"bold"}}>
            •	Usage Data
            </Text>
            <Text style={{color:"black",marginTop:15,padding:15}}>
            Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
              </Text>
              <Text style={{color:"black",marginTop:15,fontSize:22,fontWeight:"bold"}}>
            •	Cookies
            </Text>
            <Text style={{color:"black",marginTop:15,padding:15}}>
            Cookies are small files stored on your device (computer or mobile device).
             </Text>
              <Text style={{color:"black",marginTop:15,fontSize:22,fontWeight:"bold"}}>
              Information Collection and Use
            </Text>
            <Text style={{color:"black",marginTop:15,padding:15}}>
            We collect several different types of information for various purposes to provide and improve our Service to you.
             </Text>
              <Text style={{color:"black",marginTop:15,fontSize:22,fontWeight:"bold"}}>
              Types of Data Collected
            </Text>
            <Text style={{color:"black",marginTop:15,padding:15}}>
            Personal Data
While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
 </Text>
            <Text style={{color:"black"}}>
            •	Email address
            </Text>
            <Text style={{color:"black"}}>
            •	First name and last name
            </Text>
            <Text style={{color:"black"}}>
            •	Phone number
            </Text>
            <Text style={{color:"black"}}>
            •	Address, State, Province, ZIP/Postal code, City
            </Text>
            <Text style={{color:"black"}}>
            •	Cookies and Usage Data 
            </Text>
              <Text style={{color:"black",marginTop:15,fontSize:22,}}>
              Usage Data
            </Text>
            <Text style={{color:"black",marginTop:15,padding:15}}>
            We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device ("Usage Data").
            {"\n"}
            {"\n"}
This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
{"\n"}
            {"\n"}
When you access the Service by or through a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.
</Text>
            <Text style={{color:"black",padding:15}}>
            Tracking & Cookies Data
            </Text>
            <Text style={{color:"black",padding:15}}>
            We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.   {"\n"}
            {"\n"}
Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.   {"\n"}
            {"\n"}
You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.

            </Text>
            <Text style={{color:"black",padding:15}}>
            Examples of Cookies we use:
            </Text>
            <Text style={{color:"black",padding:15}}>
            •	Session Cookies. We use Session Cookies to operate our Service.
            {"\n"}
            {"\n"}

•	Preference Cookies. We use Preference Cookies to remember your preferences and various settings.
            {"\n"}
            {"\n"}
•	Security Cookies. We use Security Cookies for security purposes.
            {"\n"}
            {"\n"}

            </Text>
              <Text style={{color:"black",marginTop:15,fontSize:22,fontWeight:"bold"}}>
              Use of Data
            </Text>
            <Text style={{color:"black",padding:15}}>
            •	To provide and maintain the Service   {"\n"}
            {"\n"}
•	To notify you about changes to our Service   {"\n"}
            {"\n"}
•	To allow you to participate in interactive features of our Service when you choose to do so   {"\n"}
            {"\n"}
•	To provide customer care and support   {"\n"}
            {"\n"}
•	To provide analysis or valuable information so that we can improve the Service   {"\n"}
            {"\n"}
•	To monitor the usage of the Service   {"\n"}
            {"\n"}
•	To detect, prevent and address technical issues

            </Text>
            <Text style={{color:"black",marginTop:15,fontSize:22,fontWeight:"bold"}}>
            Transfer Of Data
            </Text>
            <Text style={{color:"black",padding:15}}>
            Your information, including Personal Data, may be transferred to - and maintained on - computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction. {"\n"}
            {"\n"}
If you are located outside United Kingdom and choose to provide information to us, please note that we transfer the data, including Personal Data, to United Kingdom and process it there. {"\n"}
            {"\n"}
Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer. {"\n"}
            {"\n"}
laundary.com will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information. {"\n"}
            {"\n"}

            </Text>
            <Text style={{color:"black",padding:15,fontSize:19}}>
            Disclosure Of Data
            {"\n"}
            {"\n"}
Legal Requirements

            </Text>
            <Text style={{color:"black",padding:15}}>
            laundary.com may disclose your Personal Data in the good faith belief that such action is necessary to:
            </Text>
            <Text style={{color:"black",}}>
            •	To comply with a legal obligation {"\n"}
            {"\n"}
•	To protect and defend the rights or property of laundary.com {"\n"}
            {"\n"}
•	To prevent or investigate possible wrongdoing in connection with the Service {"\n"}
            {"\n"}
•	To protect the personal safety of users of the Service or the public {"\n"}
            {"\n"}
•	To protect against legal liability

            </Text>
            <Text style={{color:"black",marginTop:15,fontSize:22,fontWeight:"bold"}}>
            Security of Data
            </Text>
            <Text style={{color:"black",padding:15}}>
            The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
          </Text>
            <Text style={{color:"black",marginTop:15,fontSize:22,fontWeight:"bold"}}>
            Service Providers
            </Text>
            <Text style={{color:"black",padding:15,}}>
            We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.
These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
Analytics
We may use third-party Service Providers to monitor and analyze the use of our Service.

            </Text>
            <Text style={{color:"black",marginTop:15,fontSize:22,fontWeight:"bold"}}>
            •	Unity Analytics
            </Text>
            <Text style={{color:"black",padding:15}}>
            Unity Analytics is provided by Unity Technologies.
For more information on what type of information Unity Analytics collects, please visit their Privacy Policy page: https://unity3d.com/legal/privacy-policy

            </Text>
            <Text style={{color:"black",marginTop:15,fontSize:22,fontWeight:"bold"}}>
            Links to Other Sites
            </Text>
            <Text style={{color:"black",padding:15,}}>
            Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.

            </Text>
            <Text style={{color:"black",marginTop:15,fontSize:22,fontWeight:"bold"}}>
            Children's Privacy
            </Text>
            <Text style={{color:"black",padding:15,}}>
            We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
            {"\n"}
            {"\n"}
We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.
            {"\n"}
            {"\n"}
You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.

            </Text>

            <Text style={{color:"black",marginTop:15,fontSize:22,fontWeight:"bold"}}>
            Contact Us
            </Text>
            <Text style={{color:"black",padding:15}}>
            If you have any questions about this Privacy Policy, please contact us:
            </Text>
            <Text style={{color:"black",padding:15}}>
            •	By email: websitewireframe@mail.com {"\n"}
            {"\n"}
•	By visiting this page on our website: http://laundary.com/login-register {"\n"}
            {"\n"}
•	By phone number: +44 333 333 333 {"\n"}
            {"\n"}

Privacy Policy of http://laundary.com/

            </Text>
        

            
                </View>
            </AppContainer >
        );
    }
}

let mapStateToProps = state => {
    return {
        userInfo: state.root.userInfo,
    };
};
const mapDispatchToProps = dispatch => {
    return {
        storeUserInfo: () => {
            dispatch(storeUserInfo())
        }
    }
}

export default connect(mapStateToProps, mapDispatchToProps)(Privacy);